version: "2.1"
services:
  elk:
    image: sebp/elk:670
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
