## query exampple
GET https://api.ebay.com/buy/browse/v1/item_summary/search?q=cody%20bellingers&limit=100
Authorization: Bearer <accessToken>

GET https://api.ebay.com/buy/browse/v1/item/v1|173012503335|0
Authorization: Bearer <accessToken>

## Client credentials grant using sandbox
POST https://api.sandbox.ebay.com/identity/v1/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic <B64 encoded of client_id:client_secret>

grant_type=client_credentials&scope=https://api.ebay.com/oauth/api_scope%20https://api.ebay.com/oauth/api_scope/buy.guest.order

## get item list using sandbox
GET https://api.sandbox.ebay.com/buy/browse/v1/item_summary/search?q=cody%20bellingers&limit=100
Authorization: Bearer <accessToken>

## Client credentials grant using production
POST https://api.ebay.com/identity/v1/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic <B64 encoded of client_id:client_secret>

grant_type=client_credentials&scope=https://api.ebay.com/oauth/api_scope

## get item list using production
GET https://api.ebay.com/buy/browse/v1/item_summary/search?q=cody%20bellingers&limit=100
Authorization: Bearer <accessToken>

## Get top level category id
GET http://open.api.ebay.com/Shopping?callname=GetCategoryInfo&appid=<Cient ID>&version=967&siteid=0&CategoryID=-1&IncludeSelector=ChildCategories
Authorization: Bearer <accessToken>

## Get child category id of 64482(Sports Mem, Cards &amp; Fan Shop)
GET http://open.api.ebay.com/Shopping?callname=GetCategoryInfo&appid=<Cient ID>&version=967&siteid=0&CategoryID=64482&IncludeSelector=ChildCategories
Authorization: Bearer <accessToken>

## Get child category id of 212(Sports Trading Cards)
GET http://open.api.ebay.com/Shopping?callname=GetCategoryInfo&appid=<Cient ID>&version=967&siteid=0&CategoryID=212&IncludeSelector=ChildCategories
Authorization: Bearer <accessToken>

## example get complete list for category="Sports Trading Cards" and keywork="hobby box -break" from 2019-04-01 to 2019-04-02
GET http://svcs.ebay.com/services/search/FindingService/v1
   ?OPERATION-NAME=findCompletedItems
   &SERVICE-VERSION=1.7.0
   &SECURITY-APPNAME=<Cient ID>
   &RESPONSE-DATA-FORMAT=JSON
   &REST-PAYLOAD
   &keywords=hobby%20box%20-break
   &categoryId=212
   &itemFilter(0).name=SoldItemsOnly
   &itemFilter(0).value=true
   &itemFilter(1).name=EndTimeFrom
   &itemFilter(1).value=2019-04-01T00:00:00.000Z
   &itemFilter(2).name=EndTimeTo
   &itemFilter(2).value=2019-04-02T00:00:00.000Z
   &sortOrder=EndTimeSoonest
   &paginationInput.pageNumber=1
Authorization: Bearer <accessToken>

